name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Render Deployment
    - uses: sws2apps/render-deployment@v1.2.0
      with:
       serviceId: ${{secrets.RENDERSERVICEID}}
       apiKey: ${{secrets.RENDERAPIKEY}} 
